[package]
name = "raphpdf"
version = "0.1.1"
authors = ["sekhmet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf_form_ids = "0.6.0"
unidecode = "0.3.0"
